infinitered/apisauce

README.md

Probably what you wanted to say.

will be 'called' reads better.

---

README.md
lib/apisauce.js
test/paramsTest.js
test/verbTests.js

- Add two new non-data methods: LINK and UNLINK
- See https://tools.ietf.org/html/draft-snell-link-method-12

Add LINK and UNLINK methods

---

README.md

Hey Steve
I thought your response from gitter the other day was so good that it should be immortalised. Plus, adding this detail answers one of the questions that I had in my head when I first looked at apisauce.
Keep up the good work!
🙌

So quotable, it had to get into the Readme.

---

README.md

Before it had a syntax error :)

Fix typo in Transforms example

---

README.md
dist/apisauce.js
lib/apisauce.js
package.json
test/asyncRequestTransformTests.js

Mutations were happening anyway.  Also drops `p-waterfall` because it's just serial now.

Changes async from chain to mutate.

---

README.md

Fixed typo in addAsyncRequestTransform

---

README.md

Fixes the asyncRequestTransform example again.

---

.babelrc
package.json
rollup.config.js

Tested on a real application also 🎉

:hammer: change babel stage preset to stage-3

---

.babelrc
dist/apisauce.js
package.json
rollup.config.js

~Not tested on a real application ⚠️~
Tested on my application and fixes **chrome 34** 🎉

:hammer: Switch to fast async

---

README.md
lib/apisauce.js
package.json
rollup.config.js

Was only using 2 functions, so I just brought them in.

Removes ramdasauce dependency.

---

lib/apisauce.js

This is just getting us ready for esnext module builds.

Switches to named imports for ramda.

---

lib/apisauce.js

This pr addresses issue #96 when intercepter bugs http requests, causing response to be undefined.

Fixed the problem of getting error when response is undefined

---

lib/apisauce.d.ts
package.json

Hello!
I've been using your library for a react-native application for a while, we made some typescript definitions for it. Thought I'd contribute them back in case anybody else wanted them?
If you're not interested, I'll put them in DefinitelyTyped, but otherwise I'd rather they stay with the repository they're for.

Add typescript definitions

---

.gitignore
lib/apisauce.d.ts
lib/apisauce.js
lib/apisauce.ts
package.json
test/unknown-error.test.js

* property originalError with original AxiosError
* add test for adding property originalError
* edit ts defs
* add prettier config in package.json
* add gitignore for ".vscode" dir

add new property 'originalError' for response (#147)

---

README.md

📝 updated docs to add 0.15 to readme

---

README.md
lib/apisauce.ts

✨ exposes the detection logic functions

---

apisauce.d.ts
lib/apisauce.ts
test/cancellation.test.js

add cancellation imports

---

apisauce.d.ts

fix setHeaders parameter type

---

package.json

Bumping Axios version.
Fixes #223

Bump axios version

---

apisauce.d.ts
lib/apisauce.ts
test/async-response-transform.test.js

Added async response feature. Aslo added test cases for the asyc response.

 Added AddAsyncResponseTransform 

---

README.md
apisauce.d.ts
lib/apisauce.ts

We can making request with raw config. This is usefull for making dynamic api call.

Expose doRequest as apisauce.any() method

---

package.json

The issue is with rollup https://rollupjs.org/guide/en/#error-this-is-undefined which assigns this to undefined
This is workaround and needs to be fixed in the upcoming releases﻿

Fix circle ci gloablThis error

---

lib/apisauce.ts

Fix `Cannot read properties of undefined (reading 'status')` issue

---

package.json

Fixes issues with RN 0.79 (#331)
Axios PR can be found here  https://github.com/axios/axios/pull/6933

Upgrade Axios to 1.10.0
