infinitered/apisauce

- lib/apisauce.js
- test/responseTransformTests.js
In a response transform, it should be totally legit to swap things out and reassign them.
That's the whole point.  You're transforming it!
```js
myApi.addResponseTransform(response => {
response.data = { ... } // camelize keys is a great example
}) 
```
Fixes #42.
> Adds support for reassignments within response transforms.

- lib/apisauce.js
- test/headers.test.js
This addresses issue #94 and adds a way to delete a header.
> Add a way to delete a header

- .babelrc
- package.json
- rollup.config.js
This makes it so browser applications using this library don't bundle the entire ramda library in their production builds. Reduced our gziped build size by 40kb!
> Added babel-plugin-ramda

- .babelrc
- lib/apisauce.js
- lib/apisauce.ts
- package.json
- rollup.config.js
- tsconfig.json
This just gets us up and running with TypeScript.  `fast-async` was causing some issues with the latest React Native.  I didn't realize it was doing hacky stuff, so I'm ejecting.
I'll sweep through the library and rebuild it with TypeScript first-class, but this solves the immediate problem.
This works well on React Native 0.45.1 and the latest `create-react-app`.
Addresses #108.
> Starts the conversion to TypeScript.

- lib/apisauce.d.ts
- package.json
Fixes issue:
```
node_modules/apisauce/dist/apisauce.d.ts
(96,16): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context
```
Resulting in TypeScript 2.6 due to breaking changes introduced.
See: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts
> Fix for breaking changes in typescript 2.6

- lib/apisauce.d.ts
I propose this change because in this case:
```
class MyApi {
....
public async getPage (id: number) {
const response = await this.api.get('page', { id }) as apisauce.ApiResponse<Root>
if (!response.ok) {
throw new Error(response.problem)
}
// response will be ApiOkResponse<Root> right ?
return response
}
}
```
You will get this error if declaration is set to true in your tsconfig.json:
`Exported method has or is using name 'ApiOkResponse' from external module 'a/file/path/apisauce' but cannot be named`.
> export ApiOkResponse & ApiErrorResponse

- apisauce.d.ts
Allows `baseURL` to be `undefined`. This is needed to do something like this: 
```
baseURL: process.env.MY_ENVIRONMENT_VARIABLE
```
> baseURL is string or undefined

- lib/apisauce.ts
- package.json
Typescript was complaining about the types of the predicate functions being used in ramda cond calls. This was causing tests to fail. Using curryN allows the functions to remain the same, but typescript no longer complains. Tests are passing.
Original errors:
In `getProblemFromError`:
In `getProblemFromStatus`:
Tests:
> Use curryN for predicate functions

- package.json
This bumps the `npm-run-all` dependency to 4.1.5 to avoid the malicious dependency issue with `flatmap-stream`. 
https://github.com/mysticatea/npm-run-all/issues/153
Since this is a dev dependency, there should be any risk to the package.
> Bump npm-run-all dev dependency to safe version

- package.json
See https://github.com/axios/axios/pull/1485 which was shipped with v0.19.0
CVE - https://nvd.nist.gov/vuln/detail/CVE-2019-10742
> Upgrade axios to address CVE-2019-10742

- apisauce.d.ts
Allow ApiErrorResponse to have his own type of data on ApiReponse with fallback if not specified
> Typescript update def

- apisauce.d.ts
- lib/apisauce.ts
- test/config.test.js
This PR add the ability to pass the already created axios instance in the config. This is issue [#205](https://github.com/infinitered/apisauce/issues/205).
> Add the ability to pass the already created axios instance in the config

- apisauce.d.ts
Fixes type issue in https://github.com/infinitered/apisauce/pull/222
> axiosInstance should be optional in ApisauceConfig

- apisauce.d.ts
Hi! 
This is a follow up to #219, which introduced a second type parameter used when the error response has a different structure. However, when adding types to actual API calls (HTTP methods) I noticed that this ApiErrorResponse type is not utilized.
This PR fixes it by adding a second parameter `U = T` to all HTTP method calls.
All the remaining changes are style fixes introduced by linter commit hook.
> Utilizes ApiErrorResponse<U> in all of the HTTP methods

- apisauce.d.ts
> Fixed typings for headers in ApiResponse

- package.json
I [discovered an issue](https://github.com/facebook/react-native/issues/30181) when using apisauce with one of our endpoints.
Our server runs on ASP.NET and returns a byte order mark in responses. Axios wasn't correctly handling this prior to v0.20.0-0 which meant JSON.parse would blow up.
Axios released v0.20.0-0 and v0.20.0 which fixed this particular issue, but introduced a TypeScript compilation error which has been fixed in v0.21.0.
More info:
- https://github.com/axios/axios/releases/tag/v0.21.0
- https://github.com/axios/axios/releases/tag/v0.20.0-0
> Update axios to v0.21.0

- package.json
This PR updates `axios` to version `0.21.1` due the [SSRF vulnerability](https://snyk.io/vuln/SNYK-JS-AXIOS-1038255) found in previous versions
> feat(deps): Update axios to v0.21.1

- package.json
In https://github.com/infinitered/apisauce/pull/260 I forgot that the new umd build also needs to be included in the package.json "files" section to be included in releases. Sorry about that @chakrihacker.
Any chance you could merge this, and release as 2.1.1 or something? Thanks again for considering!
> Include umd build in release

- README.md
> Add documentation to cancel request

- lib/apisauce.ts
- package.json
- Update `axios` to latest, in order to pick up vulnerability fix
- Don't default to `null` for POST `data`, since `axios` will JSON.stringify that as "null" (instead of sending an empty payload, as before)
I verified locally with my app. When only updating `axios` to 0.21.4 (using yarn's `resolutions` feature), my app was broken as one of my POST requests was sending "null" as the payload body. With this PR, it's working as expected: an empty payload instead.
Fixes https://github.com/infinitered/apisauce/issues/276
> fix: update axios and fix default value for 'data'

- test/_server.js
- test/async-request-transform.test.js
- test/async-response-transform.test.js
- test/async.test.js
- test/cancellation.test.js
- test/data.test.js
- test/headers.test.js
- test/monitor.test.js
- test/params.test.js
- test/post-data.test.js
- test/request-transform.test.js
- test/response-transform.test.js
- test/set-base-url.test.js
- test/speed.test.js
- test/status.test.js
- test/timeout.test.js
- test/verbs.test.js
Thanks to @shellscape for the heads-up on this!
We were getting random failures in our test suite due to the tests not waiting for the server(s) to start before running the tests.
This changes `createServer` to be an async function, which waits for the server to start before initiating the tests.
> Fixes random test failures by waiting for server to start

- .babelrc
- README.md
- apisauce.d.ts
- examples/github.js
- lib/apisauce.ts
- package.json
- rollup.config.js
- test/_server.js
- test/async-request-transform.test.js
- test/async-response-transform.test.js
- test/async.test.js
- test/cancellation.test.js
- test/data.test.js
- test/headers.test.js
- test/monitor.test.js
- test/params.test.js
- test/post-data.test.js
- test/request-transform.test.js
- test/response-transform.test.js
- test/set-base-url.test.js
- test/speed.test.js
- test/status.test.js
- test/timeout.test.js
- test/verbs.test.js
This PR removes Ramda from our production build of apisauce. (It's still present in devDependencies because I didn't feel like untangling the tests.)
```
commonjs    umd
With Ramda:     7.6k  19.2k
Without:        6.6k   5.8k
```
As you can see, the size win is significant -- 1k less for commonjs and 13k less for umd (not sure why umd has such a huge win, but i'll take it).
At some point it would be nice to remove Ramda from the tests too, but that's a chore.
> Removing Ramda (from prod build) and going from 19k to 6k

- apisauce.d.ts
- tsconfig.json
With the latest update (2.1.4), I'm getting an error:
```
node_modules/apisauce/apisauce.d.ts:96:27 - error TS2315: Type 'AxiosRequestConfig' is not generic.
96   any: <T, U = T>(config: AxiosRequestConfig<T>) => Promise<ApiResponse<T, U>>
~~~~~~~~~~~~~~~~~~~~~
```
This update fixes the AxiosRequestConfig type to remove the generic, which apparently has gone away.
> Fix axios types

- lib/apisauce.ts
- package.json
- tsconfig.json
This fixes vulnerabilities in the axios library: [CVE-2022-0155](https://nvd.nist.gov/vuln/detail/CVE-2022-0155) and [CVE-2022-0536](https://nvd.nist.gov/vuln/detail/CVE-2022-0536).
There are a couple of things to consider if this PR is worth merging:
* There are a [few breaking changes](https://github.com/axios/axios/blob/master/CHANGELOG.md) in axios along the way from 0.21.4 to 0.26.1
* Axios used the [AbortController type](https://github.com/axios/axios/issues/4124) from the DOM library and now doesn't. The upgrade broke a type and the fix was to add "dom" to the tsconfig. Really not sure if that is the correct work around or not.
* The upgrade needed the [Omit utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) which wasn't added until 3.5.1, …
> fix(deps): upgrade axios and typescript

- README.md
https://github.com/infinitered/apisauce/issues/50 was helpful for me to understand an unexpected issue with testing. Hopefully it'll be helpful to others who have similar issues. 
In my case, we are using axois-mock-adapter for mocking api requests. I think this is an extremely common package and pattern. We upgraded apisauce from 1.21.2 to 1.21.4, and all of the mocks stopped working. 
@skellock's [comment](https://github.com/infinitered/apisauce/issues/50#issuecomment-305764519) helped us to identify the issue, and when we looked through the code we found that 1.21.3 [clones the axios instance](https://github.com/ctimmerm/axios-mock-adapter/blob/v1.21.3/src/index.js#L51) which [was not happening in 1.21.2](https://github.com/ctimmerm/axios-mock-adapter/blob/v1.21.2/src/index.js#L48). I …
> Add testing example to README

- .circleci/config.yml
- package.json
- test/_server.js
Fixes #307 (axios was not fully upgraded on 3.0.0 as planned).
Also fixed an issue when using nodejs v17+ as the http.createServer function uses ipv6 by default and didn't listen on 127.0.0.1 as previous nodes did.
Note: while this is technically a breaking change, the break was supposed to happen in 3.0.0, so we will release this as 3.0.1 and deprecate 3.0.0.
> fix: Upgrades axios to 1.4.0 and fixes Node v17+ ipv6 issue in tests

- package.json
- test/_server.js
- test/async-request-transform.test.js
- test/async-response-transform.test.js
- test/config.test.js
- test/monitor.test.js
- test/request-transform.test.js
- test/response-transform.test.js
Using an internal tool ("flame"), I replaced ramda and ramdasauce with vanilla javascript equivalents.
> Removed ramda and ramdasauce from tests using GPT-4

- package.json
Ref. #323
This PR updates axios package to 1.7.7 to address some vulnerabilities in axios.
https://github.com/advisories/GHSA-jchw-25xp-jwwc
https://github.com/advisories/GHSA-8hc4-vh64-cxmj
I couldn't get the ava tests to run locally unfortunately (but #314) and I've only tested this inside my own RN project with only basic usage of apisauce so no guarantees here.
@jamonholmgren Thanks for taking my request at the React Universe conferanse. Would be cool if you guys could spend a few hours to update this project one day :)
> Update axios to 1.7.7 and bump version to 3.1.0

- lib/apisauce.ts
- test/_server.js
- test/data.test.js
The use of a logical OR when converting the response incorrectly assigns `null` if the body is a falsy value and has been replaced with a `??`
I observed that if the response body is `false` or any other falsy value, the data inside the response object is `null`. If instead the body is `true`, the data object is correctly `true`.
When converting the axios response, the use of the logical OR shortcuts falsy values to be `null`. 
The OR in question has been swapped with a nullish coaleshing operator to only shortcut on null values.
I also added a test case for this exact scenario, let me know if that is unwanted
> Fix nullish coaleshing on axios response conversion
